# Site settings
title: ILLIXR 1.0
email:
description: Illinois Extended Reality Benchmark Suite
baseurl: /
url: https://illixr.github.io/

twitter_username:
github_username:

# Build settings
markdown: kramdown
